apiVersion: v1
kind: Pod
metadata: 
  name: webapp-pod
  # The label is used to link Service to a Pod.
  # The key "component" is random. You could very well use "foo: bar" and use the same key value pair in Service to refer to this Pod.
  labels:
    component: mywebapp-pod
spec:
  containers:
    - name: webapp-container
      image: vaibhavdesai137/multi-containers-workflow-webapp:latest
      ports:
        - containerPort: 3000

# Used as:
# kubectl apply -f webapp-pod.yml

# Going foward, we'll use "Deployment" kind and not "Pod" anymore
# Because with "Deployment", we get to specify replicas, etc.
# "Deployment" is declarative compared to "Pod" which is imperative i.e. you need to start/stop pods, etc. 
