apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: mywebapp-pod
  template:
    metadata:
      labels:
        component: mywebapp-pod
    spec:      
      containers:
        - name: webapp-container
          image: vaibhavdesai137/multi-containers-workflow-webapp:latest
          ports:
            - containerPort: 3000

# Used as:
# kubectl apply -f webapp-deployment.yml

# Going foward, we'll use "Deployment" kind and not "Pod" anymore
# Because with "Deployment", we get to specify replicas, etc.
# "Deployment" is declarative compared to "Pod" which is imperative i.e. you need to start/stop pods, etc. 
