
#
# Refer to webapp-deployment.yml for explanation of some of the important keys
#

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: workerapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: workerapp-pod
  template:
    metadata:
      labels:
        component: workerapp-pod
    spec:      
      containers:
        - name: workerapp-container
          image: vaibhavdesai137/multi-containers-workflow-workerapp
          env:
            # These env vars are referenced in our workerapp image in keys.js
            # Using the name of the "Service" to reach the redis pod
            - name: REDIS_HOST
              value: redis-clusterip-service
            - name: REDIS_PORT
              value: '6379'
# 
# Also, no other "Service" in pur cluster needs to talk to workerapp.
# So, no "Service" is needed for this guy.
# It simply gets events from postgres insert calls and updates redis after.
#